### PR TITLE
Update from Phore upstream v1.2.2

### PR DESCRIPTION
**Pull request by wqking**
DON'T merge this PR to master branch. Please create a new branch named update-v1.2.2 and merge there.
And when merging it, be sure to keep the commit history, don't squash the PR into a single commit.

This update has some problems that we need to investigate.
When running this update on mainnet, it reports error "incorrect proof of work (DGW pre-fork)" at block 37 and the sync can't continue. The PoW related code was not changed in this update.
When I tried the send-qt downloaded from the official site, send-qt doesn't sync at all and report error "Check your wallet version, there is a new protocol on the network.".
We need to make send-qt works, then see if it has issues on block 37.

### CODE REVIEW

**Comment by wqking** [comment]
I build the master and do a test, the sync gets stuck at block 37 for PoW verification error, same as the one in the PR.

**Comment by squidicuzz** [comment]
> I build the master and do a test, the sync gets stuck at block 37 for PoW verification error, same as the one in the PR.

I have the same issue.  It was a missed problem between version `1.2.1.0` and `1.2.1.5`. I am not sure exactly what the change or issue is yet..  Version `1.2.1.0` should not have this issue and is able to sync.

The warning about protocol version is just an alert message about a protocol version change, and should not effect anything.

**Comment by squidicuzz** [comment]
> When I tried the send-qt downloaded from the official site, send-qt doesn't sync at all and report error "Check your wallet version, there is a new protocol on the network.".

Please try adding some nodes manually.  I am not sure if the seed nodes listed in the older version are still online.  Ignore the protocol version warning..

Try these nodes to get synced up:
- `fr.socialsend.io`
- `de.socialsend.io`
- `us-e1.socialsend.io`
- `us-e2.socialsend.io`

**Comment by wqking** [comment]
I will create the PR to https://github.com/TheSocialSendProject/SocialSend

**Pull request closed without merging**
